'use client'

import { useEffect, useRef, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { createClient } from '@/lib/supabase/client'
import { getYouTubeThumbnail, getYouTubeEmbedUrl } from '@/lib/youtube'

gsap.registerPlugin(ScrollTrigger)

type Project = {
  id:       number | string
  title:    string
  category: string
  year:     string
  desc:     string
  tags:     string[]
  gradient:      string
  span:          string
  accent:        string
  youtube_id?:   string | null
  thumbnail_url?: string | null
}

const PROJECTS: Project[] = [
  {
    id:       1,
    title:    'Nexus',
    category: 'AI Feature Film',
    year:     '2025',
    desc:     'A dystopian sci-fi epic about emergent AI consciousness — produced entirely with our Neural Cinema pipeline over six weeks.',
    tags:     ['Sci-Fi', 'Feature', '2hr 15min'],
    gradient: 'from-cyan-900/80 via-blue-900/60 to-[#0a0a18]',
    span:     'lg:col-span-2 lg:row-span-2',
    accent:   '#22d3ee',
  },
  {
    id:       2,
    title:    'Tesla Odyssey',
    category: 'Brand Campaign',
    year:     '2025',
    desc:     'A 360° brand campaign — 6 films, 40+ digital assets, delivered in three weeks.',
    tags:     ['Automotive', 'Campaign'],
    gradient: 'from-amber-900/70 to-[#0a0a18]',
    span:     '',
    accent:   '#f59e0b',
  },
  {
    id:       3,
    title:    'Silent Protocol',
    category: 'Web Series',
    year:     '2024',
    desc:     '8-episode espionage thriller streamed to 12M viewers in month one.',
    tags:     ['Thriller', '8 Episodes'],
    gradient: 'from-violet-900/70 to-[#0a0a18]',
    span:     '',
    accent:   '#a78bfa',
  },
  {
    id:       4,
    title:    'Aurora',
    category: 'Digital Commercial',
    year:     '2025',
    desc:     'Luxury fragrance "Aurora" — shot in virtual Iceland with AI weather simulation.',
    tags:     ['Beauty', '60s Cut'],
    gradient: 'from-pink-900/70 to-[#0a0a18]',
    span:     '',
    accent:   '#f472b6',
  },
  {
    id:       5,
    title:    'EchoVerse',
    category: 'IP Development',
    year:     '2024',
    desc:     'A transmedia universe spanning 3 feature films, a game, and 2 comic series — all built from a single AI-generated IP bible.',
    tags:     ['Transmedia', 'IP', 'Universe'],
    gradient: 'from-emerald-900/70 via-teal-900/50 to-[#0a0a18]',
    span:     'lg:col-span-2',
    accent:   '#34d399',
  },
  {
    id:       6,
    title:    'Phantom Lens',
    category: 'Virtual Production',
    year:     '2025',
    desc:     'Award-winning action short — 100% of environments generated by our Visual Genesis engine on an LED volume stage.',
    tags:     ['Action', 'Virtual Prod.'],
    gradient: 'from-indigo-900/70 to-[#0a0a18]',
    span:     '',
    accent:   '#6366f1',
  },
]

export default function Portfolio() {
  const sectionRef = useRef<HTMLElement>(null)
  const [filter,       setFilter]       = useState('All')
  const [selected,     setSelected]     = useState<Project | null>(null)
  const [youtubeModal, setYoutubeModal] = useState<string | null>(null)
  const [projects,     setProjects]     = useState<Project[]>(PROJECTS)

  // Fetch from Supabase; fall back to hardcoded demo data if DB is empty
  useEffect(() => {
    const supabase = createClient()
    supabase
      .from('portfolio_projects')
      .select('*')
      .order('display_order', { ascending: true })
      .then(({ data }) => {
        if (data && data.length > 0) {
          setProjects(
            data.map((p, i) => ({
              id:            p.id,
              title:         p.title,
              category:      p.category,
              year:          p.year,
              desc:          p.description ?? '',
              tags:          p.tags ?? [],
              gradient:      p.gradient,
              span:          '',
              accent:        p.accent,
              youtube_id:    p.youtube_id,
              thumbnail_url: p.thumbnail_url,
            }))
          )
        }
      })
  }, [])

  const ALL_CATS = ['All', ...Array.from(new Set(projects.map(p => p.category)))]
  const visible  = filter === 'All' ? projects : projects.filter(p => p.category === filter)

  useEffect(() => {
    const ctx = gsap.context(() => {
      gsap.fromTo('.portfolio-heading',
        { opacity: 0, y: 50 },
        { opacity: 1, y: 0, duration: 0.9, ease: 'power3.out',
          scrollTrigger: { trigger: '.portfolio-heading', start: 'top 85%' } }
      )
    }, sectionRef)
    return () => ctx.revert()
  }, [])

  return (
    <section id="portfolio" ref={sectionRef} className="relative section-padding overflow-hidden">
      <div className="absolute inset-0 bg-[#07070f]" />
      <div className="absolute inset-0 grid-bg opacity-25" />
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent" />

      <div className="container-narrow relative z-10">
        {/* Heading */}
        <div className="portfolio-heading flex flex-col md:flex-row md:items-end justify-between gap-6 mb-12">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full glass-light mb-5 text-xs uppercase tracking-[0.18em] text-emerald-400">
              <span className="w-1 h-1 rounded-full bg-emerald-400" />
              Featured Work
            </div>
            <h2 className="text-4xl md:text-6xl font-black tracking-tight">
              Work That<br/>
              <span className="text-gradient">Speaks Itself</span>
            </h2>
          </div>
          <p className="text-gray-400 max-w-xs md:text-right leading-relaxed">
            A selection of recent productions pushing the boundary of what AI-assisted cinema can achieve.
          </p>
        </div>

        {/* Filter tabs */}
        <div className="flex flex-wrap gap-2 mb-10">
          {ALL_CATS.map((cat) => (
            <button
              key={cat}
              onClick={() => setFilter(cat)}
              className={`cursor-none px-4 py-1.5 rounded-full text-xs font-medium border transition-all duration-300 ${
                filter === cat
                  ? 'bg-white text-black border-white'
                  : 'text-gray-500 border-white/10 hover:text-white hover:border-white/25'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Project grid */}
        <motion.div layout className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 auto-rows-[280px] gap-5">
          <AnimatePresence>
            {visible.map((project) => (
              <motion.div
                key={project.id}
                layout
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.9 }}
                transition={{ duration: 0.4, ease: [0.22, 1, 0.36, 1] }}
                className={`portfolio-card group relative rounded-2xl overflow-hidden cursor-none border border-white/6
                            bg-gradient-to-br ${project.gradient} ${project.span}`}
                onClick={() => {
                  if (project.youtube_id) {
                    setYoutubeModal(project.youtube_id)
                  } else {
                    setSelected(project)
                  }
                }}
              >
                {/* Thumbnail / YouTube thumbnail or gradient */}
                {(project.thumbnail_url || project.youtube_id) && (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={project.thumbnail_url ?? getYouTubeThumbnail(project.youtube_id!)}
                    alt={project.title}
                    className="portfolio-img absolute inset-0 w-full h-full object-cover opacity-70"
                    loading="lazy"
                  />
                )}
                {!(project.thumbnail_url || project.youtube_id) && (
                  <div className="portfolio-img absolute inset-0 bg-gradient-to-br from-transparent to-black/30" />
                )}

                {/* Grid pattern overlay */}
                <div className="absolute inset-0 grid-bg opacity-20" />

                {/* Category + year badge */}
                <div className="absolute top-4 left-4 flex items-center gap-2">
                  <span className="px-2.5 py-1 glass-light rounded-full text-[10px] uppercase tracking-wider text-gray-300">
                    {project.category}
                  </span>
                </div>
                <span className="absolute top-4 right-4 text-[11px] text-gray-500">{project.year}</span>

                {/* Hover overlay */}
                <div className="portfolio-overlay absolute inset-0 flex flex-col justify-end p-6"
                  style={{ background: `linear-gradient(to top, ${project.accent}22 0%, rgba(0,0,0,0.85) 100%)` }}
                >
                  <div className="transform translate-y-4 group-hover:translate-y-0 transition-transform duration-400">
                    <p className="text-xs text-gray-400 mb-2 line-clamp-3">{project.desc}</p>
                    <div className="flex flex-wrap gap-1.5 mb-4">
                      {project.tags.map(t => (
                        <span key={t} className="px-2 py-0.5 rounded-full text-[10px] border border-white/15 text-gray-300">
                          {t}
                        </span>
                      ))}
                    </div>
                    <button className="cursor-none inline-flex items-center gap-2 px-4 py-2 rounded-full text-xs font-medium text-white border border-white/30 hover:bg-white/10 transition-colors">
                      {project.youtube_id ? 'Watch Project' : 'View Project'}
                      {project.youtube_id ? (
                        <svg className="w-3.5 h-3.5" viewBox="0 0 24 24" fill="currentColor">
                          <path d="M8 5v14l11-7z"/>
                        </svg>
                      ) : (
                        <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                          <path strokeLinecap="round" strokeLinejoin="round" d="M17 8l4 4m0 0l-4 4m4-4H3"/>
                        </svg>
                      )}
                    </button>
                  </div>
                </div>

                {/* Bottom info (always visible) */}
                <div className="absolute bottom-0 left-0 right-0 p-5 bg-gradient-to-t from-black/60 to-transparent">
                  <h3 className="text-xl font-bold text-white leading-tight group-hover:opacity-0 transition-opacity duration-300">
                    {project.title}
                  </h3>
                </div>

                {/* Glow border on hover */}
                <div
                  className="absolute inset-0 rounded-2xl pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-500"
                  style={{ boxShadow: `inset 0 0 0 1px ${project.accent}44` }}
                />
              </motion.div>
            ))}
          </AnimatePresence>
        </motion.div>

        {/* CTA */}
        <div className="mt-14 text-center">
          <button className="cursor-none group inline-flex items-center gap-2 px-7 py-3.5 rounded-full border border-white/15 text-gray-300 hover:text-white hover:border-white/30 transition-all text-sm">
            View Full Portfolio
            <svg className="w-4 h-4 group-hover:translate-x-1 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M17 8l4 4m0 0l-4 4m4-4H3"/>
            </svg>
          </button>
        </div>
      </div>

      {/* Project detail modal */}
      <AnimatePresence>
        {selected && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] flex items-center justify-center p-6"
            onClick={() => setSelected(null)}
          >
            <div className="absolute inset-0 bg-black/80 backdrop-blur-xl" />
            <motion.div
              initial={{ scale: 0.85, opacity: 0, y: 40 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.85, opacity: 0, y: 40 }}
              transition={{ type: 'spring', stiffness: 300, damping: 30 }}
              className={`relative w-full max-w-lg rounded-3xl border border-white/10 overflow-hidden p-8
                          bg-gradient-to-br ${selected.gradient}`}
              onClick={(e) => e.stopPropagation()}
            >
              <button
                className="cursor-none absolute top-5 right-5 w-8 h-8 flex items-center justify-center rounded-full glass-light text-gray-400 hover:text-white"
                onClick={() => setSelected(null)}
              >✕</button>
              <div className="mb-2 text-xs uppercase tracking-widest" style={{ color: selected.accent }}>
                {selected.category} · {selected.year}
              </div>
              <h3 className="text-4xl font-black text-white mb-4">{selected.title}</h3>
              <p className="text-gray-300 text-base leading-relaxed mb-6">{selected.desc}</p>
              <div className="flex flex-wrap gap-2 mb-8">
                {selected.tags.map(t => (
                  <span key={t} className="px-3 py-1 rounded-full text-xs border border-white/15 text-gray-300">{t}</span>
                ))}
              </div>
              {selected.youtube_id && (
                <button
                  onClick={() => { setSelected(null); setYoutubeModal(selected.youtube_id!) }}
                  className="cursor-none w-full py-3.5 rounded-full font-medium text-white transition-all"
                  style={{ background: `linear-gradient(135deg, ${selected.accent}cc, ${selected.accent}66)` }}
                >
                  Watch Project
                </button>
              )}
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* YouTube player modal */}
      <AnimatePresence>
        {youtubeModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[120] flex items-center justify-center p-4 sm:p-8"
            onClick={() => setYoutubeModal(null)}
          >
            <div className="absolute inset-0 bg-black/95 backdrop-blur-xl" />
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              transition={{ type: 'spring', stiffness: 300, damping: 30 }}
              className="relative w-full max-w-4xl aspect-video"
              onClick={e => e.stopPropagation()}
            >
              <iframe
                src={getYouTubeEmbedUrl(youtubeModal, true)}
                className="w-full h-full rounded-2xl"
                allow="autoplay; encrypted-media; picture-in-picture"
                allowFullScreen
                title="Project video"
              />
              <button
                onClick={() => setYoutubeModal(null)}
                className="cursor-none absolute -top-10 right-0 flex items-center gap-1.5 text-sm text-gray-400 hover:text-white transition-colors"
              >
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                  <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
                Close
              </button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </section>
  )
}
