-- ================================================================
-- NextEdgeAI — Seed: Sample Portfolio Projects
-- Run in: Supabase Dashboard → SQL Editor → New Query
-- ================================================================

insert into portfolio_projects
  (title, category, year, description, tags, gradient, accent, youtube_id, thumbnail_url, display_order, is_featured)
values
  (
    'Nexus',
    'AI Feature Film',
    '2025',
    'A dystopian sci-fi epic about emergent AI consciousness — produced entirely with our Neural Cinema pipeline over six weeks.',
    array['Sci-Fi', 'Feature Film', '2hr 15min'],
    'from-cyan-900/80 via-blue-900/60 to-[#0a0a18]',
    '#22d3ee',
    null,
    null,
    1,
    true
  ),
  (
    'Tesla Odyssey',
    'Advertising Campaign',
    '2025',
    'A 360° brand campaign — 6 films, 40+ digital assets — delivered in three weeks for global markets.',
    array['Automotive', 'Brand Campaign', 'Multi-platform'],
    'from-amber-900/70 via-orange-900/40 to-[#0a0a18]',
    '#f59e0b',
    null,
    null,
    2,
    true
  ),
  (
    'Silent Protocol',
    'Web Series',
    '2024',
    '8-episode espionage thriller streamed to 12M viewers in month one — shot entirely on virtual LED stages.',
    array['Thriller', 'Web Series', '8 Episodes'],
    'from-violet-900/70 via-purple-900/40 to-[#0a0a18]',
    '#a78bfa',
    null,
    null,
    3,
    false
  ),
  (
    'Aurora',
    'Digital Commercial',
    '2025',
    'Luxury fragrance "Aurora" — shot in virtual Iceland with AI weather simulation and generative particle effects.',
    array['Beauty', 'Luxury', '60s Cut'],
    'from-pink-900/70 via-rose-900/40 to-[#0a0a18]',
    '#f472b6',
    null,
    null,
    4,
    false
  ),
  (
    'EchoVerse',
    'IP Development',
    '2024',
    'A transmedia universe spanning 3 feature films, a game, and 2 comic series — all built from a single AI-generated IP bible.',
    array['Transmedia', 'IP', 'Universe'],
    'from-emerald-900/70 via-teal-900/50 to-[#0a0a18]',
    '#34d399',
    null,
    null,
    5,
    true
  ),
  (
    'Phantom Lens',
    'Virtual Production',
    '2025',
    'Award-winning action short — 100% of environments generated by our Visual Genesis engine on an LED volume stage.',
    array['Action', 'Virtual Production', 'Short Film'],
    'from-indigo-900/70 via-blue-900/40 to-[#0a0a18]',
    '#6366f1',
    null,
    null,
    6,
    false
  );
